export const ApIConstant = {
  UPDATE_LODING_STATE: 'UPDATE_LODING_STATE',
  API_CREATE_USER_ACCOUNT_LOAD: 'API_CREATE_USER_ACCOUNT_LOAD',
  API_CREATE_USER_ACCOUNT_SUCCESS: 'API_CREATE_USER_ACCOUNT_SUCCESS',
  API_CREATE_USER_ACCOUNT_ERROR: 'API_CREATE_USER_ACCOUNT_ERROR',
  API_CREATE_USER_ACCOUNT_RESET: 'API_CREATE_USER_ACCOUNT_RESET',
  API_LOGIN_LOAD: 'API_LOGIN_LOAD',
  API_LOGIN_SUCCESS: 'API_LOGIN_SUCCESS',
  API_LOGIN_ERROR: 'API_LOGIN_ERROR',
  API_LOGIN_RESET: 'API_LOGIN_RESET',
} as const;
