import { StyleSheet } from "react-native";
import { colors } from "../../theme/colors";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.surface,
  },
  scrollContent: {
    flexGrow: 1,
  },
  screen: {
    backgroundColor: colors.surface,
    flex: 1,
    width: "100%",
  },
  header: {
    alignItems: "center",
    backgroundColor: colors.primary,
    height: 190,
    overflow: "hidden",
    paddingTop: 60,
    position: "relative",
  },
  headerOrbLarge: {
    borderRadius: 110,
    height: 220,
    left: -56,
    position: "absolute",
    top: -76,
    width: 220,
  },
  headerOrbSmall: {
    borderRadius: 76,
    height: 152,
    position: "absolute",
    right: -24,
    top: 26,
    width: 152,
  },
  headerRibbon: {
    borderRadius: 40,
    height: 88,
    position: "absolute",
    right: -40,
    top: 44,
    transform: [{ rotate: "-18deg" }],
    width: 220,
  },
  headerArc: {
    borderRadius: 82,
    borderWidth: 18,
    height: 164,
    left: -34,
    position: "absolute",
    top: 58,
    width: 164,
  },
  headerDotRow: {
    flexDirection: "row",
    gap: 8,
    position: "absolute",
    right: 26,
    top: 28,
  },
  headerDot: {
    borderRadius: 4,
    height: 8,
    width: 8,
  },
  logoAura: {
    borderRadius: 46,
    height: 92,
    left: "50%",
    marginLeft: -46,
    position: "absolute",
    top: 42,
    width: 92,
  },
  logoBadge: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderRadius: 14,
    borderWidth: 1,
    height: 58,
    justifyContent: "center",
    shadowColor: "#0C4A4A",
    shadowOffset: {
      width: 0,
      height: 12,
    },
    shadowOpacity: 0.16,
    shadowRadius: 18,
    width: 58,
  },
  logoMark: {
    height: 28,
    position: "relative",
    width: 28,
  },
  logoCircle: {
    backgroundColor: colors.primary,
    borderRadius: 14,
    height: 28,
    position: "absolute",
    right: 0,
    top: 0,
    width: 28,
  },
  logoCut: {
    backgroundColor: colors.surface,
    height: 28,
    left: 0,
    position: "absolute",
    top: 0,
    width: 10,
  },
  content: {
    backgroundColor: colors.surface,
    borderTopLeftRadius: 60,
    flex: 1,
    marginTop: -50,
    paddingBottom: 28,
    paddingHorizontal: 24,
    paddingTop: 38,
  },
  title: {
    color: "#1F1F1F",
    fontSize: 22,
    fontWeight: "700",
    marginBottom: 28,
    textAlign: "center",
  },
  formGroup: {
    gap: 14,
  },
  fieldBlock: {
    gap: 6,
  },
  fieldCard: {
    backgroundColor: colors.surface,
    borderColor: "#F4F4F5",
    borderRadius: 16,
    borderWidth: 1,
    elevation: 3,
    paddingHorizontal: 14,
    paddingVertical: 12,
    shadowColor: "#D4D9E2",
    shadowOffset: {
      width: 0,
      height: 8,
    },
    shadowOpacity: 0.18,
    shadowRadius: 16,
  },
  fieldCardError: {
    borderColor: "#F0B6B8",
  },
  fieldLabel: {
    color: "#1F1F1F",
    fontSize: 12,
    fontWeight: "600",
    marginBottom: 6,
  },
  fieldRow: {
    alignItems: "center",
    flexDirection: "row",
  },
  fieldControl: {
    flex: 1,
  },
  fieldValueWrap: {
    minHeight: 20,
    justifyContent: "center",
  },
  fieldInput: {
    color: "#1F1F1F",
    fontSize: 14,
    paddingVertical: 0,
  },
  fieldPlaceholderText: {
    color: "#C1C4CC",
  },
  fieldAccessory: {
    marginLeft: 12,
  },
  passwordAccessoryRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
  },
  accessoryButton: {
    alignItems: "center",
    justifyContent: "center",
  },
  helperText: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
    paddingHorizontal: 4,
  },
  errorText: {
    color: "#D14343",
    fontSize: 12,
    fontWeight: "500",
    paddingHorizontal: 4,
  },
  registerButton: {
    marginTop: 24,
  },
  footer: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
    marginTop: 36,
  },
  footerText: {
    color: "#4B5563",
    fontSize: 13,
  },
  footerLink: {
    color: "#111111",
    fontSize: 13,
    fontWeight: "700",
  },
  modalOverlay: {
    backgroundColor: "rgba(15, 23, 42, 0.32)",
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: 20,
  },
  calendarCard: {
    backgroundColor: colors.surface,
    borderRadius: 26,
    elevation: 10,
    padding: 20,
    shadowColor: "#0F172A",
    shadowOffset: {
      width: 0,
      height: 18,
    },
    shadowOpacity: 0.18,
    shadowRadius: 24,
  },
  calendarHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 18,
  },
  calendarNavButton: {
    alignItems: "center",
    borderRadius: 12,
    height: 36,
    justifyContent: "center",
    width: 36,
  },
  calendarNavButtonDisabled: {
    opacity: 0.35,
  },
  calendarNavText: {
    color: colors.primary,
    fontSize: 18,
    fontWeight: "700",
  },
  calendarTitle: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: "700",
  },
  weekRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  weekDayText: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: "700",
    textAlign: "center",
    width: `${100 / 7}%`,
  },
  calendarGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
  },
  dayCell: {
    alignItems: "center",
    borderRadius: 12,
    height: 40,
    justifyContent: "center",
    marginBottom: 8,
    width: `${100 / 7}%`,
  },
  dayCellSelected: {
    backgroundColor: colors.primary,
  },
  dayCellText: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: "500",
  },
  dayCellTextMuted: {
    color: "#B7C0D1",
  },
  dayCellTextDisabled: {
    color: "#D2D8E4",
  },
  dayCellTextSelected: {
    color: colors.white,
    fontWeight: "700",
  },
  calendarCloseButton: {
    alignItems: "center",
    backgroundColor: colors.primary,
    borderRadius: 12,
    marginTop: 10,
    paddingVertical: 12,
  },
  calendarCloseText: {
    color: colors.white,
    fontSize: 14,
    fontWeight: "700",
  },
});
