import { StyleSheet } from "react-native";
import { colors } from "../../theme/colors";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.surface,
  },
  scrollContent: {
    flexGrow: 1,
  },
  card: {
    backgroundColor: colors.primary,
    flex: 1,
    width: "100%",
  },
  header: {
    alignItems: "center",
    backgroundColor: colors.primary,
    height: 190,
    overflow: "hidden",
    paddingTop: 87,
    position: "relative",
  },
  headerOrbLarge: {
    borderRadius: 110,
    height: 220,
    left: -56,
    position: "absolute",
    top: -76,
    width: 220,
  },
  headerOrbSmall: {
    borderRadius: 76,
    height: 152,
    position: "absolute",
    right: -24,
    top: 26,
    width: 152,
  },
  headerRibbon: {
    borderRadius: 40,
    height: 88,
    position: "absolute",
    right: -40,
    top: 44,
    transform: [{ rotate: "-18deg" }],
    width: 220,
  },
  headerArc: {
    borderRadius: 82,
    borderWidth: 18,
    height: 164,
    left: -34,
    position: "absolute",
    top: 58,
    width: 164,
  },
  headerDotRow: {
    flexDirection: "row",
    gap: 8,
    position: "absolute",
    right: 26,
    top: 28,
  },
  headerDot: {
    borderRadius: 4,
    height: 8,
    width: 8,
  },
  logoAura: {
    borderRadius: 46,
    height: 92,
    left: "50%",
    marginLeft: -46,
    position: "absolute",
    top: 70,
    width: 92,
  },
  logoBadge: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderRadius: 14,
    borderWidth: 1,
    height: 58,
    justifyContent: "center",
    shadowColor: "#0C4A4A",
    shadowOffset: {
      width: 0,
      height: 12,
    },
    shadowOpacity: 0.16,
    shadowRadius: 18,
    width: 58,
  },
  logoMark: {
    height: 28,
    position: "relative",
    width: 28,
  },
  logoCircle: {
    backgroundColor: colors.primary,
    borderRadius: 14,
    height: 28,
    position: "absolute",
    right: 0,
    top: 0,
    width: 28,
  },
  logoCut: {
    backgroundColor: colors.surface,
    height: 28,
    left: 0,
    position: "absolute",
    top: 0,
    width: 10,
  },
  content: {
    backgroundColor: colors.surface,
    borderTopLeftRadius: 60,
    flex: 1,
    paddingBottom: 28,
    paddingHorizontal: 24,
    paddingTop: 38,
  },
  title: {
    color: "#1F1F1F",
    fontSize: 22,
    fontWeight: "700",
    marginBottom: 34,
    textAlign: "center",
  },
  formGroup: {
    gap: 14,
  },
  fieldBlock: {
    gap: 6,
  },
  fieldCard: {
    backgroundColor: colors.surface,
    borderColor: "#F4F4F5",
    borderRadius: 16,
    borderWidth: 1,
    elevation: 3,
    paddingHorizontal: 14,
    paddingVertical: 12,
    shadowColor: "#D4D9E2",
    shadowOffset: {
      width: 0,
      height: 8,
    },
    shadowOpacity: 0.18,
    shadowRadius: 16,
  },
  fieldCardError: {
    borderColor: "#F0B6B8",
  },
  fieldLabel: {
    color: "#1F1F1F",
    fontSize: 12,
    fontWeight: "600",
    marginBottom: 6,
  },
  fieldRow: {
    alignItems: "center",
    flexDirection: "row",
  },
  fieldIconWrap: {
    alignItems: "center",
    height: 22,
    justifyContent: "center",
    width: 24,
  },
  fieldControl: {
    flex: 1,
    marginLeft: 10,
  },
  fieldInput: {
    color: "#1F1F1F",
    fontSize: 14,
    paddingVertical: 0,
  },
  fieldAccessory: {
    marginLeft: 10,
  },
  errorText: {
    color: "#D14343",
    fontSize: 12,
    fontWeight: "500",
    paddingHorizontal: 4,
  },
  passwordToggleButton: {
    alignItems: "center",
    backgroundColor: "#F6F8FB",
    borderColor: "#E4E9F2",
    borderRadius: 12,
    borderWidth: 1,
    height: 34,
    justifyContent: "center",
    width: 34,
  },
  passwordToggleButtonActive: {
    backgroundColor: "#E9F7F7",
    borderColor: "#B8E4E4",
  },
  optionsRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 18,
  },
  rememberRow: {
    alignItems: "center",
    flexDirection: "row",
  },
  checkbox: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderColor: "#D8E0ED",
    borderRadius: 5,
    borderWidth: 1.4,
    height: 18,
    justifyContent: "center",
    marginRight: 8,
    width: 18,
  },
  checkboxChecked: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  checkboxCheck: {
    backgroundColor: colors.white,
    borderRadius: 2,
    height: 7,
    width: 7,
  },
  rememberText: {
    color: colors.textSecondary,
    fontSize: 13,
    fontWeight: "500",
  },
  forgotText: {
    color: colors.primary,
    fontSize: 13,
    fontWeight: "700",
  },
  loginButton: {
    marginTop: 22,
  },
  socialSection: {
    marginTop: 26,
  },
  socialDivider: {
    alignItems: "center",
    flexDirection: "row",
    marginBottom: 18,
  },
  socialDividerLine: {
    backgroundColor: "#E7EAF0",
    flex: 1,
    height: 1,
  },
  socialDividerText: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: "600",
    marginHorizontal: 12,
  },
  socialButtons: {
    flexDirection: "row",
    gap: 16,
    justifyContent: "center",
  },
  socialButton: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderColor: "#E9EDF4",
    borderRadius: 18,
    borderWidth: 1,
    elevation: 3,
    height: 58,
    justifyContent: "center",
    shadowColor: "#CBD4E3",
    shadowOffset: {
      width: 0,
      height: 8,
    },
    shadowOpacity: 0.14,
    shadowRadius: 14,
    width: 58,
  },
  socialButtonPressed: {
    opacity: 0.96,
    transform: [{ scale: 0.995 }],
  },
  socialIconImage: {
    height: 24,
    width: 24,
  },
  footer: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
    marginTop: 40,
  },
  footerText: {
    color: "#4B5563",
    fontSize: 13,
  },
  footerLink: {
    color: "#111111",
    fontSize: 13,
    fontWeight: "700",
  },
});
